routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::namespace('Admin')->prefix('dashboard')->name('dashboard.')->group(function (){

    //Route Authenticate
    Route::group(['namespace' => 'Auth', 'middleware' => 'admin_guest'], function(){
        Route::group(['prefix' => 'login', 'as' => 'login.'], function(){

            Route::get('/', 'LoginController@index')->name('index');
            Route::post('/', 'LoginController@login')->name('login');
        });
    });

    Route::get('logout', function(){
        \Auth::guard('admin')->logout();
        return redirect()->route('dashboard.login.index');
    })->name('logout');


    Route::group(['middleware' => 'admin_auth'], function (){
        Route::get('/', function(){
            return view('admin.index');
        })->name('index');


        Route::group(['prefix' => 'category', 'as' =>'category.'], function(){
            Route::post('data', 'CategoryController@data')->name('data');
            Route::post('search', 'CategoryController@search')->name('search');

            Route::resource('', 'CategoryController')->parameters([
                '' => 'category?'
            ])->except(['create', 'edit']);
        });

        Route::group(['prefix' => 'posts', 'as' => 'posts.'], function(){

            Route::post('data', 'PostsController@data')->name('data');
            Route::resource('', 'PostsController')->parameters([
                '' => 'posts?'
            ])->except(['show']);
        });


        Route::group(['prefix' => 'users', 'as' => 'users.'], function(){
            Route::post('data', 'UsersController@data')->name('data');
            Route::resource('', 'UsersController')->parameters([
                '' => 'users?'
            ])->except([
                'show', 'edit', 'update', 'create'
            ]);
        });

        Route::group(['prefix' => 'comments', 'as' => 'comments.'], function(){
            Route::post('data', 'CommentController@data')->name('data');

            Route::resource('', 'CommentController')->parameters([
                '' => 'comments?'
            ])->only([
                'index', 'destroy'
            ]);
        });

        Route::group(['prefix' => 'roles', 'as' => 'roles.'], function (){
            Route::resource('', 'RoleController')->parameters([
                '' => 'roles?'
            ])->except([
                'show', 'create', 'delete',

            ]);
        });

        Route::group(['prefix' => 'admin', 'as' => 'admin.'], function (){
            Route::resource('', 'AdminController')->parameters([
                '' => 'admin?'
            ])->except([
                'show', 'update', 'create', 'edit'
            ]);
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;

Auth::routes(['verify' => true]);

Route::group(['as' => 'client.'], function(){
    Route::get('/', 'HomeController@index')->name('index');

    Route::group(['prefix' => 'p', 'as' => 'posts.'], function (){

        Route::group(['middleware' => ['verified']], function (){
            Route::post('comment/{slug}', 'PostController@storeComment')
                ->name('comment');
        });
        Route::resource('', 'PostController')->parameters([
            '' => 'posts?'
        ])->except([
            'store', 'create', 'destroy'
        ]);
    });

    Route::group(['prefix' => 'account', 'as' => 'account.', 'middleware' => ['verified']], function(){
        Route::post('password/{id}', 'AccountController@storePassword')->name('password');
        Route::resource('', 'AccountController')->parameters([
            '' => 'account?'
        ])->except([
            'show', 'edit', 'destroy', 'store', 'create'
        ]);
    });

    Route::group(['prefix' => 'category', 'as' => 'category.'], function (){
        Route::resource('', 'CategoryController')->parameters([
            '' => 'category?'
        ])->except([
            'store', 'create', 'destroy', 'index'
        ]);
    });
});

app/Models/Post.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;
class Post extends Model
{
    use Sluggable, SoftDeletes;
    protected $table = 'posts';

    protected $fillable  = [
        'id', 'title', 'slug',
        'description', 'thumb_img', 'seo_title', 'seo_keyword',
        'seo_description', 'published', 'view', 'status', 'admin_id'
    ];

    /**
     * get admin for posts
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function admin(){
        return $this->belongsTo(Admin::class, 'admin_id');
    }

    /**
     * get categories for posts
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function category(){
        return $this->belongsToMany(Categories::class, 'category_posts', 'post_id', 'category_id');
    }

    /**
     * get tags for posts
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags(){
        return $this->belongsToMany(Tag::class, 'tag_post');
    }

    public function comments(){
        return $this->hasMany(Comment::class, 'post_id');
    }

    public function getCreatedAtAttribute($date)
    {
        $locale = \App::getLocale();
        Carbon::setLocale($locale);
        $dt = Carbon::createFromFormat('Y-m-d H:i:s', $date);
        $now = Carbon::now();
        return $dt->diffForHumans($now);
    }

    /**
     * @inheritDoc
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    protected $dates = ['deleted_at'];
}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Post\PostRequest;
use App\Models\Admin;
use App\Models\Post;
use App\Repositories\Contracts\Admin\AdminRepositoryInterface;
use App\Repositories\Contracts\Post\PostRepositoryInterface;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\View\View;

class PostsController extends Controller
{
    protected $postsRepository;

    /**
     * PostsController constructor.
     * @param PostRepositoryInterface $postsRepository
     */
    public function __construct(PostRepositoryInterface $postsRepository)
    {
//        $this->authorizeResource(Post::class, 'post');
        $this->postsRepository = $postsRepository;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index()
    {
        $user = \Auth::guard('admin')->user();
        $this->authorizeForUser($user, 'viewAny', Post::class);
        return view('admin.posts.index');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function data(Request $request){
        $user = \Auth::guard('admin')->user();
        $this->authorizeForUser( $user,'viewAny', Post::class);

        $columns = $this->postsRepository->getTableColumns(['deleted_at', 'updated_at', 'created_at', 'published', 'status']);

        $limit = $request->input('length');
        $limit = ($limit) ? $limit : 10;
        $start = $request->input('start');
        $start = ($start) ? $start : 0;
        $order = $columns[$request->input('order.0.column')];
        $order = ($order) ? $order : ['id'];
        $dir = $request->input('order.0.dir');
        $dir = ($dir) ? $dir : 'desc';

        $search = $request->input('search.value');

        $posts = $this->postsRepository;
        if (Gate::forUser($user)->denies('fullPost')){
            $posts = $posts->where('admin_id', $user->id);
        }


        $posts = $posts->where(function ($q) use ($columns, $search){
            foreach($columns as $column){
                $q->orWhere($column, 'like', '%'.$search.'%');
            }
        });

        $totalData = $totalFiltered = $search ? $posts->count() : $this->postsRepository->count();

        $posts = $posts->offset($start)
            ->limit($limit)
            ->orderBy($order, $dir)->with(['admin', 'category'])->get();

        $json_data = array(
            "draw"            => intval($request->input('draw')),
            "recordsTotal"    => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data"            => $posts
        );
        return response()->json($json_data);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $user = \Auth::guard('admin')->user();
        $this->authorizeForUser( $user,'create', Post::class);
        return view('admin.posts.create');
    }

    /**
     * @param PostRequest $request
     * @return \Illuminate\Http\JsonResponse
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function store(PostRequest $request)
    {
        $user = \Auth::guard('admin')->user();
        $this->authorizeForUser( $user,'create', Post::class);
        $data = $request->all(['title', 'description', 'thumb_img', 'published']);
        $data['status'] = 1;
        $data['admin_id'] = \Auth::guard('admin')->user()->id;
        $categories = $request->input('category_id');
        $data['seo_title'] = $request->input('seo_title') ? $request->input('seo_title') : $data['title'];
        $data['seo_description'] = strip_tags(str_limit($data['description'], 100, '...'));
        try{
            $post = $this->postsRepository->create($data);
            foreach($categories as $category){
                $post->category()->attach($category);
            }
        }catch (\Exception $e){
            return response()->json([
                'error' => true,
                'msg' => $e->getMessage()
            ]);
        }
        return response()->json([
            'error' => false,
            'msg' => $post->title
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * @param $id
     * @param Post $post
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|View
     */
    public function edit(Post $post, $id)
    {
        try{
            $user = \Auth::guard('admin')->user();
            $post = $this->postsRepository->with('category')->findOrFail($id);
            if(Gate::forUser($user)->denies('update', $post)){
                return redirect()->route('dashboard.posts.index')->withErrors(['permission' => 'Bạn không có quyền truy cập']);
            }
        }catch(ModelNotFoundException $exception){
            return redirect()->route('dashboard.posts.index')->withErrors($exception->getMessage());
        }
//        dd($post);
        return view('admin.posts.update', compact('post'));
    }

    /**
     * @param PostRequest $request
     * @param $id
     * @param Post $post
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(PostRequest $request, Post $post, $id)
    {
        $data = $request->all(['title', 'description', 'thumb_img', 'published']);
        $categories = $request->input('category_id');
        try{
            $post = $this->postsRepository->findOrFail($id);
            $user = \Auth::guard('admin')->user();
            $this->authorizeForUser( $user, 'update', $post);
            $post->update($data);
            $post->category()->detach();
            $post->category()->attach($categories);
        }catch(\Exception $exception){

        }
        return response()->json([
            'updated' => true
        ]);
    }

    /**
     * @param Post $post
     * @param int $id
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response|void
     */
    public function destroy(Post $post, int $id)
    {
        $post = $this->postsRepository->findOrFail($id);
        $user = \Auth::guard('admin')->user();
        $this->authorizeForUser( $user, 'delete', $post);
        $delete = $post->delete();
        return response([
            'deleted' => $delete
        ]);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreCommentRequest;
use App\Models\Comment;
use App\Repositories\Contracts\Post\PostRepositoryInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class PostController extends Controller
{

    protected $postRepository;

    const TIME_CACHE = 1440; //1 ngay

    public function __construct(PostRepositoryInterface $postRepository)
    {
//        $this->middleware('auth');
        $this->postRepository = $postRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    public function storeComment(StoreCommentRequest $request, $slug){
        $data = $request->all('content');
        $data['user_id'] = \Auth::user()->id;
        $post = $this->postRepository->where('slug', $slug)->first();
        if (!empty($post)){
            $comment = new Comment($data);
            try{
                $post->comments()->save($comment);
            }catch (\Exception $exception){
                return redirect()->back()->with('content', 'Lỗi sự cố');
            }
            return redirect()->back()->with('content', '');
        }else{
            return redirect()->back()->with('content', 'Lỗi sự cố');
        }

    }

    /**
     * @param $slug
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function show($slug)
    {
        $post = $this->postRepository->where('slug', $slug)->with(['comments', 'category'])->first();
        if (empty($post)){
            return redirect()->route('client.index');
        }
        return view('client.posts.index', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/client/posts/index.blade.php
@extends('layouts.master')

@section('title', $post->title)
@push('style')
@endpush
@section('content')
    <!-- Type Post -->
    <article class="type-post">
        <div class="entry-cover">
            <img src="{{ asset($post->thumb_img) }}" width="770px" height="300px" alt="Blog" />
            <div class="tags">
                <a href="#" title="Nature">{{empty($post->category) ? 'Nothing' : $post->category[0]->name}}</a>
            </div>
        </div>
        <div class="entry-content">
            <h3 class="entry-title">{{ $post->title }}</h3>
            {!! $post->description !!}

            <div class="row mt-5">
                <strong>Danh Mục:</strong>
                @foreach($post->category as $category)
                    <a href="{{ route('client.category.show', $category->slug) }}" class="btn btn-outline-secondary btn-xs">{{ $category->name }}</a>
                @endforeach
            </div>
            <div class="entry-footer">
                <div class="entry-meta">
                    <span class="byline">By <a href="#" title="{{ $post->admin->full_name }}">{{ $post->admin->full_name }}</a></span>
                    <span class="post-date"><a href="#">{{ $post->created_at }}</a></span>
                </div>
                <div class="post-social">
                    <ul>
                        <li><a href="#" title="Instagram"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#" title="Youtube"><i class="fa fa-youtube"></i></a></li>
                        <li><a href="#" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </article><!-- Type Post /- -->
    <!-- About Author -->
    <div class="about-author">
        <i><img src="{{ asset($post->admin->avatar ? $post->admin->avatar : 'https://graph.facebook.com/v6.0/1753463521/picture?width=88') }}" alt="Author"></i>
        <h3>{{ $post->admin->full_name }}</h3>
        <p>
            {{ $post->admin->story }}
        </p>
        <ul>
            <li><a href="#" title="Instagram"><i class="fa fa-instagram"></i></a></li>
            <li><a href="#" title="Youtube"><i class="fa fa-youtube"></i></a></li>
            <li><a href="#" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
        </ul>
    </div><!-- About Author -->

    <!-- Comment Area -->
    <div id="comments" class="comments-area">
        <h2 class="comments-title">{{ $post->comments()->count() }} Comments</h2>
        <div class="comment-block">
            <ol class="comment-list">
                @foreach($post->comments()->with('users')->get() as $comment)
                <li class="comment byuser comment-author-admin bypostauthor even thread-odd thread-alt depth-1">
                    <div class="comment-body">
                        <footer class="comment-meta">
                            <div class="comment-author vcard">
                                <img alt="img" src="{{ asset($comment->users->avatar ? 'storage/'.$comment->users->avatar : 'https://image.ibb.co/jw55Ex/def_face.jpg') }}" class="avatar avatar-72 photo"/>
                                <b class="fn">{{ $comment->users->name }}</b>
                            </div>
                            <div class="comment-metadata">
                                <a href="#">{{ date('Y-m-d', strtotime($comment->created_at)) }}</a>
                            </div>
                        </footer>
                        <div class="comment-content">
                            <p> {{ $comment->content }}</p>
                        </div>
                        <div class="reply">
                            <a rel="nofollow" class="comment-reply-link" href="#"><i class="fa fa-reply"></i>Reply</a>
                        </div>
                    </div>
                </li>
                    @endforeach
            </ol><!-- .comment-list -->
        </div>
        <!-- Comment Form -->
        <div id="respond" class="comment-respond">
            <h2 class="comment-reply-title">Leave a Comment</h2>
            @guest()
                <a href="{{ route('login') }}">Đăng nhập để bình luận </a>
            @endguest
            @auth()
            <form method="post" id="commentform" action="{{ route('client.posts.comment', $post->slug) }}" class="comment-form">
                @csrf
                @error('content')
                <p style="color:red"><{{ $message }}/p>
                @enderror
                <p class="comment-form-comment">
                    <textarea id="content" name="content" placeholder="Enter your comment here..." rows="8"></textarea>
                </p>
                <p class="form-submit">
                    <input name="submit" class="submit" value="Post Comment" type="submit"/>
                </p>
            </form>
            @endauth
        </div><!-- Comment Form /- -->
    </div><!-- Comment Area -->
@endsection

@push('script')
@endpush