routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::namespace('Admin')->prefix('dashboard')->name('dashboard.')->group(function (){

    //Route Authenticate
    Route::group(['namespace' => 'Auth', 'middleware' => 'admin_guest'], function(){
        Route::group(['prefix' => 'login', 'as' => 'login.'], function(){

            Route::get('/', 'LoginController@index')->name('index');
            Route::post('/', 'LoginController@login')->name('login');
        });
    });

    Route::get('logout', function(){
        \Auth::guard('admin')->logout();
        return redirect()->route('dashboard.login.index');
    })->name('logout');


    Route::group(['middleware' => 'admin_auth'], function (){
        Route::get('/', function(){
            return view('admin.index');
        })->name('index');


        Route::group(['prefix' => 'category', 'as' =>'category.'], function(){
            Route::post('data', 'CategoryController@data')->name('data');
            Route::post('search', 'CategoryController@search')->name('search');

            Route::resource('', 'CategoryController')->parameters([
                '' => 'category?'
            ])->except(['create', 'edit']);
        });

        Route::group(['prefix' => 'posts', 'as' => 'posts.'], function(){

            Route::post('data', 'PostsController@data')->name('data');
            Route::resource('', 'PostsController')->parameters([
                '' => 'posts?'
            ])->except(['show']);
        });


        Route::group(['prefix' => 'users', 'as' => 'users.'], function(){
            Route::post('data', 'UsersController@data')->name('data');
            Route::resource('', 'UsersController')->parameters([
                '' => 'users?'
            ])->except([
                'show', 'edit', 'update', 'create'
            ]);
        });

        Route::group(['prefix' => 'comments', 'as' => 'comments.'], function(){
            Route::post('data', 'CommentController@data')->name('data');

            Route::resource('', 'CommentController')->parameters([
                '' => 'comments?'
            ])->only([
                'index', 'destroy'
            ]);
        });

        Route::group(['prefix' => 'roles', 'as' => 'roles.'], function (){
            Route::resource('', 'RoleController')->parameters([
                '' => 'roles?'
            ])->except([
                'show', 'create', 'delete',

            ]);
        });

        Route::group(['prefix' => 'admin', 'as' => 'admin.'], function (){
            Route::resource('', 'AdminController')->parameters([
                '' => 'admin?'
            ])->except([
                'show', 'update', 'create', 'edit'
            ]);
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;

Auth::routes(['verify' => true]);

Route::group(['as' => 'client.'], function(){
    Route::get('/', 'HomeController@index')->name('index');

    Route::group(['prefix' => 'p', 'as' => 'posts.'], function (){

        Route::group(['middleware' => ['verified']], function (){
            Route::post('comment/{slug}', 'PostController@storeComment')
                ->name('comment');
        });
        Route::resource('', 'PostController')->parameters([
            '' => 'posts?'
        ])->except([
            'store', 'create', 'destroy'
        ]);
    });

    Route::group(['prefix' => 'account', 'as' => 'account.', 'middleware' => ['verified']], function(){
        Route::post('password/{id}', 'AccountController@storePassword')->name('password');
        Route::resource('', 'AccountController')->parameters([
            '' => 'account?'
        ])->except([
            'show', 'edit', 'destroy', 'store', 'create'
        ]);
    });

    Route::group(['prefix' => 'category', 'as' => 'category.'], function (){
        Route::resource('', 'CategoryController')->parameters([
            '' => 'category?'
        ])->except([
            'store', 'create', 'destroy', 'index'
        ]);
    });
});

app/Models/Comment.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Comment extends Model
{
    use SoftDeletes;
    protected $table = 'comments';

    protected $fillable = ['user_id', 'post_id', 'content'];

    public function users(){
        return $this->belongsTo(User::class, 'user_id');
    }

    public function posts(){
        return $this->belongsTo(Post::class, 'post_id');
    }

    public function getCreatedAtAttribute($date)
    {
        $locale = \App::getLocale();
        Carbon::setLocale($locale);
        $dt = Carbon::createFromFormat('Y-m-d H:i:s', $date);
        $now = Carbon::now();
        return $dt->diffForHumans($now);
    }

    protected $dates = ['deleted_at'];
}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Repositories\Contracts\Comment\CommentRepositoryInterface;
use Illuminate\Http\Request;
use App\Models\Comment;

class CommentController extends Controller
{

    protected $commentRepository;

    public function __construct(CommentRepositoryInterface $commentRepository)
    {
        $this->commentRepository = $commentRepository;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index()
    {
        $user = \Auth::guard('admin')->user();
        $this->authorizeForUser( $user,'viewAny', Comment::class);
        return view('admin.comments.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    public function data(Request $request){
        $user = \Auth::guard('admin')->user();
        $this->authorizeForUser( $user,'viewAny', Comment::class);

        $columns = $this->commentRepository->getTableColumns(['deleted_at', 'updated_at', 'created_at']);

        $limit = $request->input('length');
        $limit = ($limit) ? $limit : 10;
        $start = $request->input('start');
        $start = ($start) ? $start : 0;
        $order = $columns[$request->input('order.0.column')];
        $order = ($order) ? $order : ['id'];
        $dir = $request->input('order.0.dir');
        $dir = ($dir) ? $dir : 'desc';


        $search = $request->input('search.value');
        $posts = $this->commentRepository->search($columns, $search);

        $totalData = $totalFiltered = $search ? $posts->count() : $this->commentRepository->count();

        $posts = $posts->offset($start)
            ->limit($limit)
            ->orderBy($order, $dir)->with(['users', 'posts'])->get();

        $json_data = array(
            "draw"            => intval($request->input('draw')),
            "recordsTotal"    => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data"            => $posts
        );
        return response()->json($json_data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy($id)
    {
        $comment = $this->commentRepository->findOrFail($id);
        $user = \Auth::guard('admin')->user();
        $this->authorizeForUser( $user, 'update', $comment);
        $delete = $comment->delete();
        return response([
            'deleted' => $delete
        ]);
    }
}

resources/views/admin/comments/index.blade.php
@extends('admin.layouts.master')

@section('parentPageTitle', 'Phản hồi')
@section('title', 'Danh sách phản hồi')

@push('style')
    <link rel="stylesheet" href="{{asset('assets/admin/plugin/datatables/css/jquery.dataTables.min.css')}}" />
@endpush

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="body">
                    <h2 class="card-inside-title">@yield('title') </h2>
                    @if (session('error'))
                        <div class="alert alert-danger text-center">{{ session('error') }}</div>
                    @endif
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable" id="comment_data">
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop


@push('script')
    <script src="{{ asset('assets/admin/plugin/datatables/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/admin/plugin/sweetalert/sweetalert.min.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                }
            });

            var table = $('#comment_data').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ],
                serverSide: true,
                responsive: true,
                ajax: {
                    url: '{{ route('dashboard.comments.data') }}',
                    method: 'post'
                },
                deferRender: true,
                columnDefs: [
                    {
                        'targets': [0],
                        'searchable': false,
                        'orderable': true,
                    },
                    {
                        'targets': [1],
                        'searchable': true,
                        'orderable': true
                    },
                    {
                        'targets': [2],
                        'searchable': false,
                        'orderable': true
                    },
                    {
                        'targets': [3],
                        'searchable': false,
                        'orderable': false
                    },
                    {
                        'targets': [4],
                        'searchable': false,
                        'orderable': false
                    }
                ],
                columns:[
                    {data: 'id', title: 'ID'},
                    {data: 'users', title: 'Tên người dùng', render:function (users) {
                            return users.name
                        }},
                    {data: 'posts', title: 'Bài đăng', render: function (posts) {
                            return posts.title
                        }
                    },
                    {data: 'content', title: 'Nội dung', render: function(content){
                        let tmp = document.createElement('p');
                        tmp.innerHTML = content;
                        return tmp.textContent || tmp.innerText || "";
                        }
                    },
                    {data: 'created_at', title: 'Ngày tạo'},
                    {data: 'id', title: 'Action', render: function(id){
                            return `
                            <a data-edit="${id}" class="btn btn-success btn-eye btn-sm"><i class="zmdi zmdi-eye"></i></a>
										<a data-delete="${id}" class="btn btn-danger btn-sm btn-delete"><i class="zmdi zmdi-delete"></i></a>`;
                        }
                    }
                ],
                autoWidth: true,
                rowID: 'id',
                'language': {
                    'search': 'Tìm kiếm:',
                    'paginate': {
                        'first': 'Đầu',
                        'last': 'Cuối',
                        'next': 'Sau',
                        'previous': 'Trước'
                    },
                    'info': 'Hiển thị _START_ đến _END_ trong _TOTAL_ kết quả',
                    'infoEmpty': 'Hiển thị 0 đến 0 trong 0 kết quả',
                    'zeroRecords': 'không có dữ liệu trong bảng'
                },
                initComplete: function () {
                    $('#comment_data').on('click', '.btn-delete', function (e) {
                        e.preventDefault();
                        let id = $(this).data('delete');
                        swal({
                            title: 'Thông báo!!!',
                            text: 'Bạn chắc chắn muốn xóa item này!!',
                            icon: 'warning'
                        }).then((willDelete) => {
                            if (willDelete) {
                                $.ajax({
                                    url: `{{ route('dashboard.comments.destroy') }}/${id}`,
                                    method: 'delete'
                                }).done(result => {
                                    if(result.deleted){
                                        swal('Thông báo', 'Bạn đã xóa thành công item', 'success').then(e =>{
                                            table.ajax.reload();
                                        });
                                    }
                                }).fail(error => {
                                    let status = error.status;
                                    if(status === 403){
                                        swal('Thông báo!!!', 'Bạn không có quyền xóa item này', 'warning');
                                    }
                                });
                            } else {
                                swal("Your imaginary file is safe!");
                            }
                        });
                    });
                }
            });
        });
    </script>
@endpush