routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::namespace('Admin')->prefix('dashboard')->name('dashboard.')->group(function (){

    //Route Authenticate
    Route::group(['namespace' => 'Auth', 'middleware' => 'admin_guest'], function(){
        Route::group(['prefix' => 'login', 'as' => 'login.'], function(){

            Route::get('/', 'LoginController@index')->name('index');
            Route::post('/', 'LoginController@login')->name('login');
        });
    });

    Route::get('logout', function(){
        \Auth::guard('admin')->logout();
        return redirect()->route('dashboard.login.index');
    })->name('logout');


    Route::group(['middleware' => 'admin_auth'], function (){
        Route::get('/', function(){
            return view('admin.index');
        })->name('index');


        Route::group(['prefix' => 'category', 'as' =>'category.'], function(){
            Route::post('data', 'CategoryController@data')->name('data');
            Route::post('search', 'CategoryController@search')->name('search');

            Route::resource('', 'CategoryController')->parameters([
                '' => 'category?'
            ])->except(['create', 'edit']);
        });

        Route::group(['prefix' => 'posts', 'as' => 'posts.'], function(){

            Route::post('data', 'PostsController@data')->name('data');
            Route::resource('', 'PostsController')->parameters([
                '' => 'posts?'
            ])->except(['show']);
        });


        Route::group(['prefix' => 'users', 'as' => 'users.'], function(){
            Route::post('data', 'UsersController@data')->name('data');
            Route::resource('', 'UsersController')->parameters([
                '' => 'users?'
            ])->except([
                'show', 'edit', 'update', 'create'
            ]);
        });

        Route::group(['prefix' => 'comments', 'as' => 'comments.'], function(){
            Route::post('data', 'CommentController@data')->name('data');

            Route::resource('', 'CommentController')->parameters([
                '' => 'comments?'
            ])->only([
                'index', 'destroy'
            ]);
        });

        Route::group(['prefix' => 'roles', 'as' => 'roles.'], function (){
            Route::resource('', 'RoleController')->parameters([
                '' => 'roles?'
            ])->except([
                'show', 'create', 'delete',

            ]);
        });

        Route::group(['prefix' => 'admin', 'as' => 'admin.'], function (){
            Route::resource('', 'AdminController')->parameters([
                '' => 'admin?'
            ])->except([
                'show', 'update', 'create', 'edit'
            ]);
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;

Auth::routes(['verify' => true]);

Route::group(['as' => 'client.'], function(){
    Route::get('/', 'HomeController@index')->name('index');

    Route::group(['prefix' => 'p', 'as' => 'posts.'], function (){

        Route::group(['middleware' => ['verified']], function (){
            Route::post('comment/{slug}', 'PostController@storeComment')
                ->name('comment');
        });
        Route::resource('', 'PostController')->parameters([
            '' => 'posts?'
        ])->except([
            'store', 'create', 'destroy'
        ]);
    });

    Route::group(['prefix' => 'account', 'as' => 'account.', 'middleware' => ['verified']], function(){
        Route::post('password/{id}', 'AccountController@storePassword')->name('password');
        Route::resource('', 'AccountController')->parameters([
            '' => 'account?'
        ])->except([
            'show', 'edit', 'destroy', 'store', 'create'
        ]);
    });

    Route::group(['prefix' => 'category', 'as' => 'category.'], function (){
        Route::resource('', 'CategoryController')->parameters([
            '' => 'category?'
        ])->except([
            'store', 'create', 'destroy', 'index'
        ]);
    });
});

resources/views/admin/layouts/auth.blade.php
<!doctype html>
<html class="no-js " lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="description" content="Responsive Bootstrap 4 and web Application ui kit.">
    <title>@yield('title')</title>
    <!-- Favicon-->
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <!-- Custom Css -->
    <link rel="stylesheet" href="{{asset('assets/admin/css/app.css')}}">
</head>

<body class="theme-blush">

<div class="authentication">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-sm-12">
                @yield('content')
                <div class="copyright text-center">
                    &copy;
                    <script>document.write(new Date().getFullYear())</script>,
                </div>
            </div>
            <div class="col-lg-8 col-sm-12">
                <div class="card">
                    <img src="{{asset('assets/images/signin.svg')}}" alt="Sign In"/>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Jquery Core Js -->
<script src="{{asset('assets/bundles/libscripts.bundle.js')}}"></script>
<script src="{{asset('assets/bundles/vendorscripts.bundle.js')}}"></script> <!-- Lib Scripts Plugin Js -->
</body>
</html>

resources/views/admin/layouts/left_sidebar.blade.php
<aside id="leftsidebar" class="sidebar">
    <div class="navbar-brand">
        <button class="btn-menu ls-toggle-btn" type="button"><i class="zmdi zmdi-menu"></i></button>
        <a href="{{ route('dashboard.index') }}"><img src="{{asset('assets/images/logo.svg')}}" width="25" alt="{{ config('app.name') }}"><span class="m-l-10">{{ config('app.name') }}</span></a>
    </div>
    <div class="menu">
        <ul class="list">
            <li>
                <div class="user-info">
                    <a class="image" href="#"><img src="{{asset('assets/images/profile_av.jpg')}}" alt="User"></a>
                    <div class="detail">
                        <h4>{{ auth()->guard('admin')->user()->full_name }}</h4>
                        <small>{{ auth()->guard('admin')->user()->roles[0]->name }}</small>
                    </div>
                </div>
            </li>
            <li class="{{ request()->routeIs('dashboard.index*') ? 'active' : '' }}">
                <a href="{{ route('dashboard.index') }}"><i class="zmdi zmdi-home"></i><span>Dashboard</span></a>
            </li>
            <li class="{{ request()->routeIs('dashboard.posts*') ? 'active' : '' }}">
                <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-apps"></i><span>Bài Đăng</span></a>
                <ul class="ml-menu">
                    <li>
                        <a href="{{ route('dashboard.posts.index') }}">Danh sách</a>
                    </li>
                    <li>
                        <a href="{{ route('dashboard.posts.create') }}">Thêm bài đăng</a>
                    </li>
                </ul>
            </li>
            <li class="{{ request()->routeIs('dashboard.category*') ? 'active' : '' }}">
                <a href="{{ route('dashboard.category.index') }}" class=""><i class="zmdi zmdi-assignment"></i><span>Quản lý danh mục</span>
                </a>
            </li>
            <li class="{{ request()->routeIs('dashboard.comments*') ? 'active' : '' }}">
                <a href="{{ route('dashboard.comments.index') }}" class=""><i class="zmdi zmdi-comments"></i><span>Quản lý phản hồi</span></a>
            </li>
            <li class="{{ request()->routeIs('dashboard.users*') ? 'active' : '' }}">
                <a href="{{ route('dashboard.users.index') }}" class=""><i class="zmdi zmdi-account"></i><span>Quản lý người dùng</span></a>
            </li>
            <li class="{{ request()->routeIs('dashboard.admin*') ? 'active' : '' }}">
                <a href="{{ route('dashboard.admin.index') }}" class=""><i class="zmdi zmdi-account"></i><span>Quản trị viên</span></a>
            </li>
            <li class="{{ request()->routeIs('dashboard.roles*') ? 'active' : '' }}">
                <a href="{{ route('dashboard.roles.index') }}" class=""><i class="zmdi zmdi-account"></i><span>Phân Quyền</span></a>
            </li>
            <li>
                <a href="{{ route('dashboard.logout') }}" class=""><i class="zmdi zmdi-close"></i><span>Đăng xuất</span></a>
            </li>
        </ul>
    </div>
</aside>

resources/views/admin/layouts/master.blade.php
<!doctype html>
<html class="no-js " lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@yield('title', config('app.name'))</title>
    <meta name="_token" content="{{csrf_token()}}">
    <!-- Favicon-->
    <link rel="icon" href="{{asset('favicon.ico')}}" type="image/x-icon">
    <link rel="stylesheet" href="{{asset('assets/admin/css/app.css')}}">
    <!-- Custom Css -->
    @stack('style')
</head>

<body class="theme-blush ls-toggle-menu">

<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="m-t-30"><img class="zmdi-hc-spin" src="{{asset('assets/images/loader.svg')}}" width="48" height="48" alt="Aero"></div>
        <p>Please wait...</p>
    </div>
</div>

<!-- Overlay For Sidebars -->
<div class="overlay"></div>

<!-- Main Search -->
<div id="search">
    <button id="close" type="button" class="close btn btn-primary btn-icon btn-icon-mini btn-round">x</button>
    <form>
        <input type="search" value="" placeholder="Search..." />
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
</div>

<!-- Right Icon menu Sidebar -->
@include('admin.layouts.menu_sidebar')


<!-- Left Sidebar -->
@include('admin.layouts.left_sidebar')

<!-- Right Sidebar -->
@include('admin.layouts.right_sidebar')


<!-- Main Content -->
<section class="content">
    <div class="body_scroll">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <h2>@yield('title')</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('dashboard.index')}}"><i class="zmdi zmdi-home"></i> {{config('app.name')}}</a></li>
                        @if (trim($__env->yieldContent('parentPageTitle')))
                            <li class="breadcrumb-item">@yield('parentPageTitle')</li>
                        @endif
                        @if (trim($__env->yieldContent('title')))
                            <li class="breadcrumb-item active">@yield('title')</li>
                        @endif
                    </ul>
                    <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <button class="btn btn-primary btn-icon float-right right_icon_toggle_btn" type="button"><i class="zmdi zmdi-arrow-right"></i></button>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            @yield('content')
        </div>
    </div>
</section>
<!-- Jquery Core Js -->
<script src="{{asset('assets/bundles/libscripts.bundle.js')}}"></script> <!-- Lib Scripts Plugin Js -->
<script src="{{asset('assets/bundles/vendorscripts.bundle.js')}}"></script> <!-- Lib Scripts Plugin Js -->

<script src="{{asset('assets/bundles/mainscripts.bundle.js')}}"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
            }
        });
    });
</script>
@stack('script')
</body>
</html>

resources/views/admin/layouts/menu_sidebar.blade.php
<div class="navbar-right">
    <ul class="navbar-nav">
        <li><a href="#search" class="main_search" title="Search..."><i class="zmdi zmdi-search"></i></a></li>
        <li><a href="javascript:void(0);" class="app_calendar" title="Calendar"><i class="zmdi zmdi-calendar"></i></a></li>
        <li><a href="javascript:void(0);" class="app_google_drive" title="Google Drive"><i class="zmdi zmdi-google-drive"></i></a></li>
        <li><a href="javascript:void(0);" class="app_group_work" title="Group Work"><i class="zmdi zmdi-group-work"></i></a></li>
        <li><a href="javascript:void(0);" class="js-right-sidebar" title="Setting"><i class="zmdi zmdi-settings zmdi-hc-spin"></i></a></li>
        <li><a href="sign-in.html" class="mega-menu" title="Sign Out"><i class="zmdi zmdi-power"></i></a></li>
    </ul>
</div>

resources/views/admin/layouts/right_sidebar.blade.php
<aside id="rightsidebar" class="right-sidebar">
    <ul class="nav nav-tabs sm">
        <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#setting"><i class="zmdi zmdi-settings zmdi-hc-spin"></i></a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="setting">
            <div class="slim_scroll">
                <div class="card">
                    <h6>Theme Option</h6>
                    <div class="light_dark">
                        <div class="radio">
                            <input type="radio" name="radio1" id="lighttheme" value="light" checked="">
                            <label for="lighttheme">Light Mode</label>
                        </div>
                        <div class="radio mb-0">
                            <input type="radio" name="radio1" id="darktheme" value="dark">
                            <label for="darktheme">Dark Mode</label>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <h6>Color Skins</h6>
                    <ul class="choose-skin list-unstyled">
                        <li data-theme="purple"><div class="purple"></div></li>
                        <li data-theme="blue"><div class="blue"></div></li>
                        <li data-theme="cyan"><div class="cyan"></div></li>
                        <li data-theme="green"><div class="green"></div></li>
                        <li data-theme="orange"><div class="orange"></div></li>
                        <li data-theme="blush" class="active"><div class="blush"></div></li>
                    </ul>
                </div>
                <div class="card">
                    <h6>General Settings</h6>
                    <ul class="setting-list list-unstyled">
                        <li>
                            <div class="checkbox rtl_support">
                                <input id="checkbox1" type="checkbox" value="rtl_view">
                                <label for="checkbox1">RTL Version</label>
                            </div>
                        </li>
                        <li>
                            <div class="checkbox ms_bar">
                                <input id="checkbox2" type="checkbox" value="mini_active">
                                <label for="checkbox2">Mini Sidebar</label>
                            </div>
                        </li>
                        <li>
                            <div class="checkbox">
                                <input id="checkbox3" type="checkbox" checked="">
                                <label for="checkbox3">Notifications</label>
                            </div>
                        </li>
                        <li>
                            <div class="checkbox">
                                <input id="checkbox4" type="checkbox">
                                <label for="checkbox4">Auto Updates</label>
                            </div>
                        </li>
                        <li>
                            <div class="checkbox">
                                <input id="checkbox5" type="checkbox" checked="">
                                <label for="checkbox5">Offline</label>
                            </div>
                        </li>
                        <li>
                            <div class="checkbox">
                                <input id="checkbox6" type="checkbox" checked="">
                                <label for="checkbox6">Location Permission</label>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</aside>