routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::namespace('Admin')->prefix('dashboard')->name('dashboard.')->group(function (){

    //Route Authenticate
    Route::group(['namespace' => 'Auth', 'middleware' => 'admin_guest'], function(){
        Route::group(['prefix' => 'login', 'as' => 'login.'], function(){

            Route::get('/', 'LoginController@index')->name('index');
            Route::post('/', 'LoginController@login')->name('login');
        });
    });

    Route::get('logout', function(){
        \Auth::guard('admin')->logout();
        return redirect()->route('dashboard.login.index');
    })->name('logout');


    Route::group(['middleware' => 'admin_auth'], function (){
        Route::get('/', function(){
            return view('admin.index');
        })->name('index');


        Route::group(['prefix' => 'category', 'as' =>'category.'], function(){
            Route::post('data', 'CategoryController@data')->name('data');
            Route::post('search', 'CategoryController@search')->name('search');

            Route::resource('', 'CategoryController')->parameters([
                '' => 'category?'
            ])->except(['create', 'edit']);
        });

        Route::group(['prefix' => 'posts', 'as' => 'posts.'], function(){

            Route::post('data', 'PostsController@data')->name('data');
            Route::resource('', 'PostsController')->parameters([
                '' => 'posts?'
            ])->except(['show']);
        });


        Route::group(['prefix' => 'users', 'as' => 'users.'], function(){
            Route::post('data', 'UsersController@data')->name('data');
            Route::resource('', 'UsersController')->parameters([
                '' => 'users?'
            ])->except([
                'show', 'edit', 'update', 'create'
            ]);
        });

        Route::group(['prefix' => 'comments', 'as' => 'comments.'], function(){
            Route::post('data', 'CommentController@data')->name('data');

            Route::resource('', 'CommentController')->parameters([
                '' => 'comments?'
            ])->only([
                'index', 'destroy'
            ]);
        });

        Route::group(['prefix' => 'roles', 'as' => 'roles.'], function (){
            Route::resource('', 'RoleController')->parameters([
                '' => 'roles?'
            ])->except([
                'show', 'create', 'delete',

            ]);
        });

        Route::group(['prefix' => 'admin', 'as' => 'admin.'], function (){
            Route::resource('', 'AdminController')->parameters([
                '' => 'admin?'
            ])->except([
                'show', 'update', 'create', 'edit'
            ]);
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;

Auth::routes(['verify' => true]);

Route::group(['as' => 'client.'], function(){
    Route::get('/', 'HomeController@index')->name('index');

    Route::group(['prefix' => 'p', 'as' => 'posts.'], function (){

        Route::group(['middleware' => ['verified']], function (){
            Route::post('comment/{slug}', 'PostController@storeComment')
                ->name('comment');
        });
        Route::resource('', 'PostController')->parameters([
            '' => 'posts?'
        ])->except([
            'store', 'create', 'destroy'
        ]);
    });

    Route::group(['prefix' => 'account', 'as' => 'account.', 'middleware' => ['verified']], function(){
        Route::post('password/{id}', 'AccountController@storePassword')->name('password');
        Route::resource('', 'AccountController')->parameters([
            '' => 'account?'
        ])->except([
            'show', 'edit', 'destroy', 'store', 'create'
        ]);
    });

    Route::group(['prefix' => 'category', 'as' => 'category.'], function (){
        Route::resource('', 'CategoryController')->parameters([
            '' => 'category?'
        ])->except([
            'store', 'create', 'destroy', 'index'
        ]);
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable, SoftDeletes;

    protected $table = 'users';

    protected $guard = 'web';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'avatar', 'dob'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $dates = [
        'deleted_at'
    ];
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Admin;
use App\Models\Post;
use App\Models\User;
use App\Repositories\Contracts\Users\UsersRepositoryInterface;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    protected $usersRepository;

    public function __construct(UsersRepositoryInterface $usersRepository)
    {
        $this->usersRepository = $usersRepository;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index()
    {
        $user = \Auth::guard('admin')->user();
        $this->authorizeForUser( $user, 'viewAny', User::class);
        return view('admin.users.index');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function data(Request $request){

        $user = \Auth::guard('admin')->user();
        $this->authorizeForUser( $user, 'viewAny', User::class);

        $columns = $this->usersRepository->getTableColumns();

        $limit = $request->input('length');
        $limit = ($limit) ? $limit : 10;
        $start = $request->input('start');
        $start = ($start) ? $start : 0;
        $order = $columns[$request->input('order.0.column')];
        $order = ($order) ? $order : ['id'];
        $dir = $request->input('order.0.dir');
        $dir = ($dir) ? $dir : 'desc';


        $search = $request->input('search.value');
        $posts = $this->usersRepository->search($columns, $search);

        $totalData = $totalFiltered = $search ? $posts->count() : $this->usersRepository->count();

        $posts = $posts->offset($start)
            ->limit($limit)
            ->orderBy($order, $dir)->get();

        $json_data = array(
            "draw"            => intval($request->input('draw')),
            "recordsTotal"    => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data"            => $posts
        );
        return response()->json($json_data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Admin  $admin
     * @return \Illuminate\Http\Response
     */
    public function destroy(Admin $admin, $id)
    {
        $admin = \Auth::guard('admin')->user();
        $user = $this->usersRepository->find($id);
        $this->authorizeForUser( $admin, 'viewAny', $user);
        return response([
            'deleted' => $user->delete()
        ]);
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.master')

@section('parentPageTitle', 'Bài Đăng')
@section('title', 'Thêm bài đăng')
@section('content')
    <form class="row" action="{{ route('dashboard.posts.store') }}" method="post" id="create_post">
        <div class="col-md-9">
            <div class="card">
                <div class="body">
                    <h2 class="card-inside-title">@yield('title')</h2>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="">Tiêu đề bài đăng</label>
                                <input type="text" name="title" id="title" class="form-control" />
                            </div>
                            <div class="form-group">
                                <label for="">Nội dung</label>
                                <textarea name="description" id="description" cols="30" rows="10"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="body">
                    <h2 class="card-inside-title">@yield('title')</h2>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <select name="published" id="published" class="form-control show-tick">
                                    <option value="1">Công khai</option>
                                    <option value="0">Lưu tạm</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <select name="category_id[]" id="category_id" multiple="multiple" class="form-control select2_category show-tick">
                                </select>
                            </div>
                            <div class="form-group">
                                    <a id="lfm" data-input="thumb_img" data-preview="holder" class="nav-link text-blue" style="color:blue!important;">
                                        <i class="fa fa-picture-o"></i> Thêm Thumb Images
                                    </a>
                                <input id="thumb_img" class="form-control" type="text" name="thumb_img">
                            </div>
                            <img id="holder" style="margin-top:15px;max-height:100px;">

                            <div class="form-group">
                                <button class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

@push('script')
    <script src="{{asset('assets/admin/plugin/select2/js/select2.min.js')}}"></script>
    <script src="{{ asset('assets/admin/plugin/ckeditor4/ckeditor.js') }}"></script>
    <script src="{{ asset('vendor/laravel-filemanager/js/stand-alone-button.js') }}"></script>
    <script src="{{asset('assets/admin/plugin/sweetalert/sweetalert.min.js')}}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('input').on('focus', function () {
                if($(this).hasClass('border border-warning')){
                    $(this).removeClass('border border-warning').next().remove();
                }
            });

            var lfm_route = "{{ url(config('lfm.url_prefix', config('lfm.prefix'))) }}";
            var options = {
                filebrowserImageBrowseUrl: `${lfm_route}?type=Images`,
                filebrowserImageUploadUrl: `${lfm_route}/upload?type=Images&_token={{csrf_token()}}`,
                filebrowserBrowseUrl: `${lfm_route}?type=Files`,
                filebrowserUploadUrl: `${lfm_route}/upload?type=Files&_token={{csrf_token()}}`
            };
            var editor = CKEDITOR.replace('description', options);
            $('#lfm').filemanager('image', {prefix: lfm_route});
            $('.select2_category').select2({
                minimumInputLength: 2,
                ajax:{
                    url: '{{ route('dashboard.category.search') }}',
                    method: 'post',
                    dataType: 'json',
                    data:function(params){
                        return {
                            q: params.term
                        };
                    },
                    processResults: function(data){
                        return {
                            results: $.map(data, function(item){
                                return {
                                    text: item.text,
                                    id: item.id,
                                    data: item
                                }
                            })
                        }
                    },
                    cache: true
                },
                escapeMarkup: function (markup) { return markup; },
            });

            $('#create_post').on('submit', function(e){
                e.preventDefault();

                $(this).find('button').attr('disabled', true);

                let form_data = new FormData($(this)[0]);
                form_data.set('description', editor.getData());
                $.ajax({
                    url: '{{ route('dashboard.posts.store') }}',
                    method: 'post',
                    processData: false,
                    contentType:false,
                    data: form_data
                }).done(function(result){
                    if(!result.error){
                        swal('Thông báo!!!', 'Thêm bài đăng thành công', 'success').then(_ =>{
                            $('input').val('');
                            editor.setData('');
                            $('.select2_category').empty();
                            $('img#holder').attr('src', '');
                        });
                    }
                }).fail(errors => {
                    let status = errors.status,
                        msg = errors.responseJSON;
                    if (status === 422){
                        let error_msg = msg.errors;
                        Object.keys(msg.errors).forEach( k =>{
                            let label = `<label id="${k}-error" class="error" for="${k}">${error_msg[k][0]}</label>`;
                            $(`#${k}`).addClass('border border-warning').after(label);
                        });
                    }
                }).always(_ =>{
                    $(this).find('button').attr('disabled', false);
                });
            })
        });
    </script>
@endpush

resources/views/admin/users/index.blade.php
@extends('admin.layouts.master')

@section('parentPageTitle', 'Người dùng')
@section('title', 'Danh sách người dùng')

@push('style')
    <link rel="stylesheet" href="{{asset('assets/admin/plugin/datatables/css/jquery.dataTables.min.css')}}" />
@endpush

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="body">
                    <h2 class="card-inside-title">@yield('title') </h2>
                    @if (session('error'))
                        <div class="alert alert-danger text-center">{{ session('error') }}</div>
                    @endif
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable" id="users_data">
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop


@push('script')
    <script src="{{ asset('assets/admin/plugin/datatables/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/admin/plugin/sweetalert/sweetalert.min.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                }
            });

            var table = $('#users_data').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ],
                serverSide: true,
                responsive: true,
                ajax: {
                    url: '{{ route('dashboard.users.data') }}',
                    method: 'post'
                },
                deferRender: true,
                columnDefs: [
                    {
                        'targets': [0],
                        'searchable': false,
                        'orderable': true,
                    },
                    {
                        'targets': [1],
                        'searchable': true,
                        'orderable': true
                    },
                    {
                        'targets': [2],
                        'searchable': false,
                        'orderable': true
                    },
                    {
                        'targets': [3],
                        'searchable': false,
                        'orderable': false
                    },
                    {
                        'targets': [4],
                        'searchable': false,
                        'orderable': false
                    }
                ],
                columns:[
                    {data: 'id', title: 'ID'},
                    {data: 'name', title: 'Tên người dùng '},
                    {data: 'email', title: 'Email'},
                    {data: 'created_at', title: 'Ngày tạo'},
                    {data: 'id', title: 'Action', render: function(id){
                            return `
                            <a data-edit="${id}" class="btn btn-success btn-eye btn-sm"><i class="zmdi zmdi-eye"></i></a>
										<a data-delete="${id}" class="btn btn-danger btn-sm btn-delete"><i class="zmdi zmdi-delete"></i></a>`;
                        }
                    }
                ],
                autoWidth: true,
                rowID: 'id',
                'language': {
                    'search': 'Tìm kiếm:',
                    'paginate': {
                        'first': 'Đầu',
                        'last': 'Cuối',
                        'next': 'Sau',
                        'previous': 'Trước'
                    },
                    'info': 'Hiển thị _START_ đến _END_ trong _TOTAL_ kết quả',
                    'infoEmpty': 'Hiển thị 0 đến 0 trong 0 kết quả',
                    'zeroRecords': 'không có dữ liệu trong bảng'
                },
                initComplete: function () {
                    $('#users_data').on('click', '.btn-delete', function (e) {
                        e.preventDefault();
                        let id = $(this).data('delete');
                        swal({
                            title: 'Thông báo!!!',
                            text: 'Bạn chắc chắn muốn xóa item này!!',
                            icon: 'warning'
                        }).then((willDelete) => {
                            if (willDelete) {
                                $.ajax({
                                    url: `{{ route('dashboard.users.destroy') }}/${id}`,
                                    method: 'delete'
                                }).done(result => {
                                    if(result.deleted){
                                        swal('Thông báo', 'Bạn đã xóa thành công item', 'success').then(e =>{
                                            table.ajax.reload();
                                        });
                                    }
                                }).fail(error => {
                                    let status = error.status;
                                    if(status === 403){
                                        swal('Thông báo!!!', 'Bạn không có quyền xóa item này', 'warning');
                                    }
                                });
                            } else {
                                swal("Your imaginary file is safe!");
                            }
                        });
                    });
                }
            });
        });
    </script>
@endpush

resources/views/admin/users/update.blade.php
@extends('admin.layouts.master')

@section('parentPageTitle', 'Bài Đăng')
@section('title', 'Cập nhật bài đăng')
@section('content')
    <form class="row" action="{{ route('dashboard.posts.update', $post->id) }}" method="post" id="update_post">
        <div class="col-md-9">
            <div class="card">
                <div class="body">
                    <h2 class="card-inside-title">{{ $post->title }}</h2>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="">Tiêu đề bài đăng</label>
                                <input type="text" name="title" id="title" class="form-control" value="{{ $post->title }}" />
                            </div>
                            <div class="form-group">
                                <label for="">Nội dung</label>
                                <textarea name="description" id="description" cols="30" rows="10">{!! $post->description !!}</textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="body">
                    <h2 class="card-inside-title">@yield('title')</h2>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <select name="published" id="published" class="form-control show-tick">
                                    <option {{$post->published ? 'selected' : ''}} value="1">Công khai</option>
                                    <option {{!$post->published ? 'selected' : ''}} value="0">Lưu tạm</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <select name="category_id[]" id="category_id" multiple="multiple" class="form-control select2_category show-tick">
                                    @foreach($post->category as $category)
                                        <option selected="selected" value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <a id="lfm" data-input="thumb_img" data-preview="holder" class="nav-link text-blue" style="color:blue!important;">
                                    <i class="fa fa-picture-o"></i> Thêm Thumb Images
                                </a>
                                <input id="thumb_img" class="form-control" type="text" value="{{ $post->thumb_img }}" name="thumb_img">
                            </div>
                            <img id="holder" style="margin-top:15px;max-height:100px;" src="{{ $post->thumb_img }}">

                            <div class="form-group">
                                <button class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

@push('script')
    <script src="{{ asset('assets/admin/plugin/select2/js/select2.min.js') }}"></script>
    <script src="{{ asset('assets/admin/plugin/ckeditor4/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/admin/plugin/sweetalert/sweetalert.min.js') }}"></script>
    <script src="{{ asset('vendor/laravel-filemanager/js/stand-alone-button.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('input').on('focus', function () {
                if($(this).hasClass('border border-warning')){
                    $(this).removeClass('border border-warning').next().remove();
                }
            });

            var lfm_route = "{{ url(config('lfm.url_prefix', config('lfm.prefix'))) }}";
            var options = {
                filebrowserImageBrowseUrl: `${lfm_route}?type=Images`,
                filebrowserImageUploadUrl: `${lfm_route}/upload?type=Images&_token={{csrf_token()}}`,
                filebrowserBrowseUrl: `${lfm_route}?type=Files`,
                filebrowserUploadUrl: `${lfm_route}/upload?type=Files&_token={{csrf_token()}}`
            };
            var editor = CKEDITOR.replace('description', options);
            $('#lfm').filemanager('image', {prefix: lfm_route});
            $('.select2_category').select2({
                minimumInputLength: 2,
                ajax:{
                    url: '{{ route('dashboard.category.search') }}',
                    method: 'post',
                    dataType: 'json',
                    data:function(params){
                        return {
                            q: params.term
                        };
                    },
                    processResults: function(data){
                        return {
                            results: $.map(data, function(item){
                                return {
                                    text: item.text,
                                    id: item.id,
                                    data: item
                                }
                            })
                        }
                    },
                    cache: true
                },
                escapeMarkup: function (markup) { return markup; },
            });

            $('#update_post').on('submit', function(e){
                e.preventDefault();

                $(this).find('button').attr('disabled', true);

                let form_data = new FormData($(this)[0]),
                    url_current_update = $(this).attr('action');
                form_data.set('description', editor.getData());
                form_data.set('_method', 'put');
                $.ajax({
                    url: url_current_update,
                    method: 'post',
                    processData: false,
                    contentType:false,
                    cache: false,
                    data: form_data
                }).done(function(result){
                    if(!result.errors){
                        swal('Thông báo!!!', 'Cập nhật thành công', 'success');
                    }
                }).fail(errors => {
                    let status = errors.status,
                        msg = errors.responseJSON;
                    if (status === 422){
                        let error_msg = msg.errors;
                        Object.keys(msg.errors).forEach( k =>{
                            let label = `<label id="${k}-error" class="error" for="${k}">${error_msg[k][0]}</label>`;
                            $(`#${k}`).addClass('border border-warning').after(label);
                        });
                    }
                }).always(_ =>{
                    $(this).find('button').attr('disabled', false);
                });
            })
        });
    </script>
@endpush